name: Feature Request
description: Suggest a new idea for this project
title: "Feature: "
body:
  - type: markdown
    attributes:
      value: "### Contact Details"

  - type: input
    id: name
    attributes:
      label: "What is your name?"
      placeholder: "ex. Sertha Taweewattana"
    validations:
      required: true

  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out this bug report!"

  - type: dropdown
    id: type
    attributes:
      label: "Type of request?"
      description: "Select the type of your request"
      options:
        - New Feature
        - Enhancement
        - Bug Fix
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: "What is the OS which you want to suggest?"
      multiple: true
      options:
        - Windows
        - MacOS
        - Linux
        - iOS
        - Android

  - type: textarea
    id: description
    attributes:
      label: "What are the details of your suggestion?"
      description: "Explain what do you want"
      placeholder: "Feature details!"
    validations:
      required: true
